Migrate to MSK
Financial-Times/upp-next-video-mapper pull request #43
Opened 2022-08-15 14:13 UTC by elenasuteva

# Description

## What

As part of the kafka migration, this PR contains the changes for migrating from old kafka to MSK.

Using the Kafka-client-go/v3 library replaced the consumer and producer of Kafka messages, updated env vars.
Start producer and cosumer in the main function, update logger to v2 and update go version to 18.
Kafka consumer lag monitor healthcheck added. 
Remove unused functions and tests are fixed.

## Why

https://financialtimes.atlassian.net/browse/UPPSF-3414 

## Anything, in particular, you'd like to highlight to reviewers

Mention here sections of code which you would like reviewers to pay extra attention to .E.g

Please check if the values of the env variables are correct.

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [x] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2022-08-16 09:07 UTC, dtvalk-ov requested changes
I've left some comments on the changes, but also the [failing checks](https://app.circleci.com/pipelines/github/Financial-Times/upp-next-video-mapper/92/workflows/11de33a2-d7dc-4b3a-bf61-f4bc3070d07e/jobs/309) should be considered and fixed

2022-08-16 09:07 UTC, dtvalk-ov commented on video/events_handler.go
> +		v.log.Errorln(err)
Suggestion: This could become v.log.WithError(err).Error("Failed to transform message")

2022-08-17 06:37 UTC, atanasdinov requested changes

2022-08-17 06:37 UTC, atanasdinov commented on utils/utils.go
> +func ReadContent(fileName string) (string, error) {
That's a helper function only used in tests. It shouldn't be exposed on any package level.

2022-08-17 06:37 UTC, atanasdinov commented on video/video_mapper.go
> +		deleteVideoMsg, err2 := v.buildAndMarshalPublicationEvent(videoModel, contentURI, lastModified, tid)
I'm really not a fan of using separate error naming. Is there an issue with value shadowing? Applies to all `err2` occurrences in the changes.

2022-08-17 06:37 UTC, atanasdinov commented on video/model.go
> +type PublicationEvent struct {
The type is not used outside of the package. Do we need it public?

2022-08-17 06:37 UTC, atanasdinov commented on video/model.go
> +const VideoSystemOrigin = "http://cmdb.ft.com/systems/next-video-editor"
I'd suggest to use `systemOrigin` as a name for this constant. The `Video` prefix is colliding with the package name so it's unnecessary and it's not used outside of the package so there's no need for it to be exported.

2022-08-17 06:37 UTC, atanasdinov commented on video/healthcheck_test.go
> +func (p *mockConsumerInstance) Start() {
This and the `Stop()` method can be removed. Also it makes more sense for the receiver to be named `c` (for consumer) instead of `p`.

2022-08-17 06:37 UTC, atanasdinov commented on video/healthcheck_test.go
> +func (p *mockConsumerInstance) MonitorCheck() error {
This check is not included in the assertions.

2022-08-17 06:37 UTC, atanasdinov commented on README.md
> +export KAFKA_ADDRESS="http://172.23.53.64:8080" ## you'll have to change the address to your queue
That's an HTTP address and not a Kafka one, please adjust it.

2022-08-17 06:37 UTC, atanasdinov commented on main.go
> +		defer func(consumer *kafka.Consumer) {
Let's also `Close()` the producer connection.

2022-08-17 07:03 UTC, elenasuteva commented on video/video_mapper.go
> +		deleteVideoMsg, err2 := v.buildAndMarshalPublicationEvent(videoModel, contentURI, lastModified, tid)
I am not a fan too but the linter error was showing a message that the err value is overriden and when I change it, linter was okay. I will try and fix this again.

2022-08-17 14:42 UTC, elenasuteva commented on utils/utils.go
> +func ReadContent(fileName string) (string, error) {
I am getting it back to the video package and make it private.

2022-08-17 14:51 UTC, elenasuteva commented on video/model.go
> +type PublicationEvent struct {
I left this probably from the refactor I've done locally then reverted. Getting it back private.

2022-08-22 07:29 UTC, atanasdinov approved these changes

2022-08-22 08:23 UTC, ilian2233 submitted a review, later dismissed

2022-08-25 11:19 UTC, elenasuteva commented
> I've left some comments on the changes, but also the [failing checks](https://app.circleci.com/pipelines/github/Financial-Times/upp-next-video-mapper/92/workflows/11de33a2-d7dc-4b3a-bf61-f4bc3070d07e/jobs/309) should be considered and fixed

`

2022-08-25 15:54 UTC, elenasuteva commented
@atanasdinov should I decrease the replicaCount from 2 to 1?

2022-08-25 16:14 UTC, atanasdinov commented
Yes, it'd be better.

2022-08-26 12:38 UTC, atanasdinov approved these changes

2022-08-26 13:56 UTC, merged